[package]
name = "grammartec"
version = "0.1.0"
authors = ["coco <coco@hexgolems.com>"]

[dependencies]
regex = "1.3.7"
lazy_static= "1.4.0"
rand = "0.7.3"
hash_by_ref = "0.1.0"
regex_mutator = {path = "../regex_mutator"}
regex-syntax = "0.6.17"
serde_derive = "1.0"
serde = "1.0"
loaded_dice = "0.2"
num = "0.2.1"
pyo3 = "0.15.0"
